// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vsoqrujavwxvhkjsjwih.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZzb3FydWphdnd4dmhranNqd2loIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEyMTY5MjAsImV4cCI6MjA2Njc5MjkyMH0.lbFLkS22a0e4p6DERM7x8nS98FW7MT8m8ADFYgbXrh0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});